included: Upupu
excluded: Pods
force_cast: warning
force_try:
  severity: warning
type_body_length:
  - 300 # warning
  - 400 # error
identifier_name:
  min_length:
    error: 0
  allowed_symbols:
    - _
