language: objective-c
osx_image: xcode9
install:
  - gem install xcpretty
  - pod install --repo-update
before_script:
  - set -o pipefail
script:
  - xcodebuild -workspace Upupu.xcworkspace -scheme 'Upupu' -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 8' -configuration Debug test | xcpretty -c
branches:
  only:
    - master
